
#### Data

This data shows the details of the different types of fossil fuels (mainly oil, gas and coal) for different countries.
This data set contains data for consumption, production, export, import, reserves, population of the different countries. 
The time frame of data is 1980-2021.
The data was published US Energy Information Analysis (EIA) 
The data can be found [here](https://ourworldindata.org/explorers/natural-resources)


#### Purpose

The purpose of the app is to:

1. Show the yearly production trend of the different types of fossil fuels for different countries.
2. Show the yearly consumption trend of the different types of fossil fuels for different countries and also try to establish a relation between consumption and population.
3. Show the reserves of the different types of fossil fuels and does it have a relation with the production of the respective fossil fuel. 
4. We also look at the export and import data of the countries and try to establish a relation between them.

It is clear from the data that for most of the countries, the consumption of the fossil fuel increases with the increase in population.The countries which are rich in a particular resource are usually found to import that commodity and vice versa. Export and Import of fossil fuels also depend upon many other factors but in this case, we take into account the consumption and population of the country and if the country does not have enough reserves or infact production, it still will import the commodity.
It also depends upon the population of the country.

#### Creator

Kumar Vatsal (kvat0001@student.monash.edu)

<details>
<summary>Session information</summary>
```{r, echo = FALSE}
sessioninfo::session_info()
```
</details>
