---
title: "Untitled"
author: "Kumar Vatsal"
date: '2022-08-14'
output: html_document
---

```{r}
resources <- read_csv("natural-resources.csv") %>%
  select(`Gas production`,`Gas consumption`,`Coal production`,`Coal consumption`,`Oil production`,`Oil consumption`,`Entity`,`Year`,`Gas reserves`,`Oil reserves`,`Coal reserves`)
 

resources2 <- read_csv("natural-resources.csv") %>%
  select(`Gas production`,`Gas consumption`,`Coal production`,`Coal consumption`,`Oil production`,`Oil consumption`,`Entity`,`Year`,`Gas reserves`,`Oil reserves`,`Coal reserves`,`Population`) %>% 
  pivot_longer(cols = `Gas production`:`Oil consumption`,
               names_to = 'type',
               values_to = 'quantity' )

resources3 <- resources2 %>% 
  select(`Entity`,`Year`,`Gas reserves`,`Oil reserves`,`Coal reserves`) %>% 
  pivot_longer(cols = `Gas reserves`:`Coal reserves`,
               names_to = 'reserve_type',
               values_to = 'quantity_reserve')
  
  







```


```{r}
p2 <- ggplot(resources2,aes(x = `Year`,
                          y= Population)) + geom_line(stat = 'identity') +
      theme_dark() +
      scale_x_continuous( breaks = seq(min(resources2$Year),
                                       max(resources2$Year), by=2)) +
      labs(x = "Year", y = "Consumption (in million)")

p2
```

```{r}
g <- ggplot(reso5, aes(Year))
g <- g + geom_line(aes(y= `Oil imports`/1000 ), colour="red")
g <- g + geom_line(aes(y= `Oil exports`), colour="green")
g



```


```{r}

rec2<- resources2 %>% filter(Entity == "India")




p2 <- ggplot(rec2,aes(x = `Year`,
                          y= )) + geom_line(stat = 'identity') +
      theme_dark() +
      scale_x_continuous( breaks = seq(min(resources2$Year),
                                       max(resources2$Year), by=2)) +
      labs(x = "Year", y = "Consumption (in million)")

    gridExtra::grid.arrange(p,p2, nrow = 2)


```



```{r}


resources4 <- read_csv("natural-resources.csv") %>%
  select(`Gas imports`,`Gas exports`,`Coal imports`,`Coal exports`,`Oil imports`,`Oil exports`,`Entity`,`Year`) %>% 
  pivot_longer(cols = `Gas imports`:`Oil exports`,
               names_to = 'type',
               values_to = 'quantity')
  




reso5 <- resources4 <- read_csv("natural-resources.csv") %>%
  select(`Gas imports`,`Gas exports`,`Coal imports`,`Coal exports`,`Oil imports`,`Oil exports`,`Entity`,`Year`) %>% 
  filter(Entity == "India")



```
```{r}
ai <- resources %>%  group_by(Entity) %>%  
  summarise(avg_oil = (mean(`Oil production`, na.rm = TRUE)/1000000))
```



